component rpmlimiter "limit spindle RPM by tool number";

pin in unsigned tool-number "tool number, in";
pin in float tool.#.max [personality] "rpm max for tool, in.n.max";
pin in float rpm-in "RPM input, in";
pin out float rpm-out "RPM output, out";
function _;
license "GPL";
author "Travis Farmer";
;;

FUNCTION(_) {
    if (rpm-in > tool_max(tool-number-1)) {
        rpm-out = tool_max(tool-number-1);
    } else {
        rpm-out = rpm-in
    }
}
