component vfd2rps "Compute the rps from an encoder velocity value";

pin in float in "velocity input value" ;
pin out float out "rps output value";


function _;
license "GPL";
author "Travis Farmer";
;;
FUNCTION(_) {
    double shiftOffset = in - 3660.00;
    double tmpout = shiftOffset / 73.775;
    if(tmpout < 0){tmpout = 0;} // make sure RPS is not negative
    out = tmpout;
}
